/**
 * This file is generated by create-hua.
 * It ensures Tailwind scans hua-ui/hua sources in both monorepo and standalone installs.
 */
const componentSafelist = [
  { pattern: /^(bg|text|border)-(?:primary|secondary|accent|neutral|success|warning|danger)(?:-(?:50|100|200|300|400|500|600|700|800|900))?$/ },
  { pattern: /^(px|py)-(?:0|1|2|3|4|5|6|8|10)$/ },
  { pattern: /^text-(?:xs|sm|base|lg|xl|2xl)$/ },
  { pattern: /^rounded-(?:none|sm|md|lg|xl|2xl|3xl|full)$/ },
  { pattern: /^shadow-(?:sm|md|lg|xl|2xl)$/ },
  { pattern: /^transition(?:-(?:all|colors|opacity|transform))?$/ },
  { pattern: /^duration-(?:75|100|150|200|300)$/ },
  { pattern: /^ease-(?:linear|in|out|in-out)$/ },
  'modal-open',
  'modal-close',
  'modal-backdrop',
  'drawer-open',
  'drawer-side',
  'drawer-content',
  'card-glow',
  'card-gradient'
];

module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './node_modules/@hua-labs/hua/**/*.{ts,tsx}',
    './node_modules/@hua-labs/motion-core/**/*.{ts,tsx}',
    './node_modules/@hua-labs/ui/**/*.{ts,tsx}'
  ],
  safelist: componentSafelist,
  theme: {
    extend: {},
  },
  plugins: [],
};
